### ISSUE TITLE
Fix "Filtered JSON" whenever there are changes/updates to JMESPath

### ISSUE THREAD

**Issue by allejo** [allejo/json-reshaper#6]
I have recorded a video demonstrating the current, broken behavior.

https://github.com/allejo/json-reshaper/assets/1246453/52f5dbf2-cf9f-4b07-bea9-ba039abbfcef

This is a multi-part issue:

- [ ] Whenever `JMESPath` is cleared or updated, the _Filtered JSON_ area needs to be updated to reflect either an empty array or error if it's an invalid type.
- [ ] Related to this bug, this `JMESPath` query is required to return an array of objects, so let's display an error if the "Filtered JSON" is not an array.
- [ ] Also, when no JMESPath is given, the _Filtered JSON_ should be identical to _From JSON_.

_See https://github.com/allejo/json-reshaper/issues/6#issuecomment-1700060442 for more details_

I've attached a ZIP of a JSON file with dummy data to use while testing.

[MOCK_DATA.json.zip](https://github.com/allejo/json-reshaper/files/12384778/MOCK_DATA.json.zip)

**Comment by masterghost2002** [comment]
Hi @allejo I think, you are looking for something like this, 
[Screencast from 2023-08-19 16-39-27.webm](https://github.com/allejo/json-reshaper/assets/55751461/c7a0e1c8-ec76-4ad3-834a-8ab9719a1f1a)

**Comment by allejo** [comment]
> Hi @allejo I think, you are looking for something like this, [Screencast from 2023-08-19 16-39-27.webm](https://github.com/allejo/json-reshaper/assets/55751461/c7a0e1c8-ec76-4ad3-834a-8ab9719a1f1a)

@masterghost2002 correct, this is the behavior I would like to have instead of what currently exists

**Comment by masterghost2002** [comment]
Sir, can you please explain little bit more about the task 2 and task 3 for better understanding

**Comment by allejo** [comment]
Sure thing @masterghost2002!

## Task 2

Let's say you're given the following input JSON (the "From JSON" section),

```json
{
  "id": 12345,
  "items": [
    {"foo": "bar"},
    {"foo": "bar"}
  ]
}
```

In order for this application to work and be able to create a multi-row CSV data file, the result after the JMESPath query should give the next part of the application an array of data; (the next part of the application is the column editor and preview). So if I give it a query of `id`, then the "Filtered JSON" would effectively have `12345` as a value. But you can't make CSV rows from a single number e.g.

If the JMESPath query results in something other than an array of objects, then display an error explaining the situation

## Task 3

If JMESPath is an empty string and the input JSON is already an array of objects, then the "Filtered JSON" should be identical to the input. However, if it's not in this shape then some sort of warning or message should appear saying that an array of objects is needed.
